import React from "react";

export default function AboutView() {
    return (
        <div>
            <h1 className="text-center font-bold text-2xl">Who Are We</h1>
            <p className="text-lg m-3">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Incidunt, magni? Reiciendis sequi doloremque, debitis, atque distinctio voluptatem labore, quisquam ipsa modi vitae nihil minima delectus porro cupiditate quia at repellat. Quibusdam vero cupiditate possimus ipsum dolores velit excepturi ea beatae dolorum temporibus! Earum soluta, explicabo ducimus reiciendis assumenda dolorem corporis beatae. Repudiandae temporibus necessitatibus nemo reprehenderit earum rerum, corrupti tenetur, soluta voluptatum quas esse ex consectetur laborum molestias vel! Ullam ipsum tempora dolore quae consectetur maxime amet nemo ratione, sunt animi deleniti, sed aliquam accusamus recusandae error. Adipisci perspiciatis dicta praesentium natus obcaecati aliquid nesciunt laboriosam voluptas iste delectus itaque ipsam rerum expedita molestias, numquam veritatis vero quisquam rem sint quasi nisi dolorem assumenda ab? Consectetur, sunt illum quae pariatur corporis architecto corrupti dolores facere officiis obcaecati facilis tempore explicabo esse cumque, quam hic tempora nam. Voluptas illum, adipisci quos quas voluptatem beatae quis, doloribus vitae sed minus odit distinctio delectus ab dolor fugit? Similique accusamus quod ad minus facilis aliquid. Impedit, hic? Nam, autem sunt veniam id in illum pariatur saepe vero, non ullam repellendus unde itaque, cupiditate necessitatibus incidunt vitae molestiae. Odit modi ratione aperiam provident nesciunt, nam incidunt est deleniti temporibus ipsum quam illo dignissimos fuga minima!</p>
            <h1 className="text-center font-bold text-2xl">What We Do</h1>
            <p className="text-lg m-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, odio! Illum esse illo at aspernatur, similique inventore impedit eius soluta, rem laboriosam beatae officiis totam nam mollitia odit ipsum nemo veniam vero maiores suscipit nostrum. Explicabo consequatur blanditiis numquam deserunt, minus aliquam! Itaque facere illum quod aspernatur quidem consequuntur tempore eos tenetur eveniet vitae labore minus voluptatum mollitia ipsum quisquam sunt quae, expedita inventore deserunt commodi autem? Reiciendis harum cumque dignissimos quasi provident, id atque consequatur a autem odio, iste earum recusandae nulla sed sint aut tempore eos qui? Inventore saepe nesciunt rem dolor aspernatur corporis, accusamus quia tempora deleniti itaque quaerat enim laborum, vero libero? Est expedita vitae amet eum delectus sed nihil quaerat, commodi id! Enim nisi dignissimos sequi minima, quibusdam voluptas suscipit sunt distinctio magnam, molestias tempore aperiam aliquid! Repellat magnam, officia quasi adipisci enim praesentium odio tempora odit accusantium magni quia deserunt officiis est iste corrupti?</p>
        </div>
    ) 
}